---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

helmDefaults:
  createNamespace: true
  wait: true
  waitForJobs: true
  timeout: 600

repositories:

  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

  - name: external-secrets
    url: https://charts.external-secrets.io

  - name: jetstack
    url: https://charts.jetstack.io

  - name: csi-driver-nfs
    url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts

  - name: csi-s3
    url: https://yandex-cloud.github.io/k8s-csi-s3/charts

#   - name: cilium
#     url: https://helm.cilium.io/

  - name: metallb
    url: https://metallb.github.io/metallb

  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

  - name: bjw-s
    url: https://bjw-s-labs.github.io/helm-charts

  - name: cloudnative-pg
    url: https://cloudnative-pg.github.io/charts

  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts/

  - name: oauth2-proxy
    url: https://oauth2-proxy.github.io/manifests

  - name: backube
    url: https://backube.github.io/helm-charts/

  - name: community-charts
    url: https://community-charts.github.io/helm-charts

  - name: nuclio
    url: https://nuclio.github.io/nuclio/charts

  - name: twuni
    url: https://twuni.github.io/docker-registry.helm
