# We are using a meta Helm chart called app-template from bwj-s.
# Reference values can be inspected there.
# Ref: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml

defaultPodOptions:
  labels: {}
  annotations: {}

controllers:
  application:
    type: deployment
    replicas: 1

    labels: {}
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      main:
        image:
          repository: ghcr.io/achetronic/magec
          tag: 0.1.0
          pullPolicy: IfNotPresent
        args: ["./magec", "--config", "/config/config.yaml"]
        ports:
          - containerPort: 8080
        env:
          REDIS_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: cache-user-credentials
                key: password
          PG_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: database-user-credentials
                key: password
        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}-ai-credentials"

persistence:
  configuration:
    enabled: true
    #name: "{{ .Release.Name }}-configuration"
    name: "{{ .Release.Name }}"
    type: configMap
    advancedMounts:
      application:
        main:
          - path: /config/config.yaml
            readOnly: true
            mountPropagation: None
            subPath: config.yaml

configMaps:
  configuration:
    enabled: true
    annotations: {}
    data:
      config.yaml: |
        server:
          port: 8081
          host: 0.0.0.0

        log:
          level: debug # debug, info, warn, error
          format: console # console, json

        # Reusable AI backends
        backends:
          # Large language models
          # Using big models to keep responses as natural and precise as possible
          - name: anthropic
            type: anthropic
            apiKey: "${AI_ANTHROPIC_API_KEY}"

          - name: openai
            type: openai
            apiKey: "${AI_OPENAI_API_KEY}"

          # Transcription models (STT)
          # Using self-hosted Parakeet TDT
          - name: local-whisper
            type: openai
            url: http://parakeet.parakeet.svc:5092/v1

          # Transcription models (TTS)
          # Using self-hosted OpenAI Edge TTS
          - name: local-tts
            type: openai
            apiKey: "sk-proj-fake-apikey"
            url: http://openai-edge-tts.openai-edge-tts.svc:5050/v1

          # Generic models
          # Not using Ollama for LLMs as GPUs are not available in the cluster,
          # but using it for calculate embeddings and tiny things
          - name: ollama
            type: openai
            url: http://localhost:11434/v1

        transcription:
          backend: local-whisper
          model: whisper-1

        llm:
          backend: anthropic
          model: claude-opus-4-5-20251101

          # backend: openai
          # model: gpt-5.1

        # TTS settings (optional)
        tts:
          backend: local-tts
          model: tts-1-hd
          voice: es-ES-AlvaroNeural
          speed: 1.1 # 0.25 to 4.0

        memory:
          session:
            redis:
              address: dragonfly-agents-cluster-00.dragonfly.svc:6379
              password: "${REDIS_PASSWORD}"
              db: 0
              ttl: 24h

          longTerm:
            embedding:
              backend: ollama
              model: nomic-embed-text

            postgres:
              connectionString: "postgres://app:${PG_PASSWORD}@postgres-agents-cluster-00-rw.postgres.svc:5432/app?sslmode=disable"

        mcpServers:
          - name: hass-mcp
            endpoint: http://hass-mcp.hass-mcp.svc:8080/mcp

service:
  backend:
    controller: application
    type: ClusterIP
    ports:
      http:
        port: 8080
        protocol: TCP

# Some stuff that is not covered by this chart
rawResources:
  ai-credentials:
    enabled: true
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    spec:
      spec:
        refreshInterval: "15s"
        secretStoreRef:
          kind: ClusterSecretStore
          name: gitlab-secret-store
        target:
          name: "{{ .Release.Name }}-ai-credentials"
        data:
          - secretKey: AI_ANTHROPIC_API_KEY
            remoteRef:
              key: AI_ANTHROPIC_API_KEY
          - secretKey: AI_OPENAI_API_KEY
            remoteRef:
              key: AI_OPENAI_API_KEY

  public-entrance:
    enabled: true
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    spec:
      spec:
        hostnames:
          - magec.tools.internal.place
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: gateway-api-extra-gateway-production
            namespace: istio
            sectionName: https-terminate
        rules:
          - backendRefs: &mainBackendRef
              - group: ""
                kind: Service
                name: magec
                port: 8080
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /
