rawResources:
  https-terminate-tls:
    enabled: true
    apiVersion: cert-manager.io/v1
    kind: Certificate
    spec:
      spec:
        secretName: https-terminate-tls
        dnsNames:
          # Internal Systems
          - congatudo.tools.internal.place
          - docker-registry.tools.internal.place # TODO: Enable authentication
          - home.tools.internal.place
          - home-assistant.tools.internal.place
          - jellyfin.tools.internal.place
          - keycloak.tools.internal.place
          - magec.tools.internal.place
          - admin.magec.tools.internal.place
          - memex.tools.internal.place
          - nuclio.tools.internal.place
          - oauth2-proxy.tools.internal.place
          - omada-controller.tools.internal.place
          - qbittorrent.tools.internal.place
          - vaultwarden.tools.internal.place

          # Public systems
          - keycloak.public.internal.place

        issuerRef:
          name: letsencrypt-production
          kind: ClusterIssuer
          group: cert-manager.io
