# Ref: https://github.com/FyraLabs/chisel-operator/blob/main/charts/chisel-operator/values.yaml

replicaCount: 1 # Right now only 1 replica is supported
# LeaderElection and multiple replicas may be supported in the future.
# For now, we recommend running only 1 replica else Chisel Operator may constantly
# recreate resources, wasting your API resources and costing you money.

# Create CRDs for Chisel Operator
createCrds: true

# Optional load balancer class handled by the operator. When empty, all LoadBalancer
# services are reconciled, matching the default behavior.
loadBalancerClass: "chisel.exit.nodes"

# Set the logger used by the operator.
# Valid options are: "logfmt", "pretty", "json", "compact"
# Default is "logfmt"
logger: "logfmt"


